If the road to the habour is flooded it is not possible anymore to go to the habour
ProjectL-Team/ProjectL pull request #53
Opened 2017-06-28 14:42 UTC by J2a0s0o0n

Knüpft an das noch kommende Minispiel und somit auch an #50.

2017-06-28 17:06 UTC, JOOpdenhoevel requested changes
Im allgemeinen gut, aber du brauchst nicht, wenn du eine Methode erweiterst, sie aus der Vater-Klasse kopieren und dann anpassen. Ich hab dir an die entsprechende Stelle geschrieben, wie das geht.

2017-06-28 17:06 UTC, Janonard commented on Source/Roads.py
> +from collections import deque
Diese Zeile muss weg, da sie unnötig ist.

2017-06-28 17:06 UTC, Janonard commented on Source/Roads.py
> +    def check_transfer_as_parent(self, subject, target):
Du musst die Implementierung der Vater-Klasse nicht 1:1 kopieren, du kannst einfach schreiben:

    if not Core.Place.check_transfer_as_parent(self, subject, target):
        return False
    else:
        # deine Sachen

Du erweiterst die Funktionalitäten ja nur und ersetzt sie nicht.

2017-06-28 19:36 UTC, JOOpdenhoevel approved these changes
So soll es sein, sehr gut!

2017-06-28 19:36 UTC, merged

2017-06-29 14:07 UTC, J2a0s0o0n commented
@Janonard hast du es getestet? Weil ich erhalte nach dem Dialog mit Hex, wenn ich zum Hafenweg gehe eine Fehlermeldung:
Error while playing a scene: An operation could not be executed!
Außerdem habe ich vergessen in Zeile 51 wieder "return False" zu schreiben.

2017-06-29 17:31 UTC, Janonard commented
Nein, habe ich nicht, ich fand es nicht notwendig, ich hätte es aber machen sollen. Du hast in Zeile 98 den Fall nicht bedacht, dass das Ziel auch etwas anderes als der Hafen sein kann. Ich liefere das gleich nach.

Aber: Die Tatsache, dass der Bug vorhanden ist zeigt auch, dass du das ganze nicht getestet hast, wir haben also beide Mist gebaut! Achte du bitte mehr darauf und ich mache es auch.

2017-06-29 17:32 UTC, Janonard commented
Am besten sollten wir uns angewöhnen am Ende einer Überprüfungsmethode immer `return False` bzw. `return True` zu schreiben, dann passiert das nicht mehr.