Dialogues and some minor text changes.
ProjectL-Team/ProjectL pull request #56
Opened 2017-07-03 20:05 UTC by Flummi3

So weit habe ich jetzt alle Dialoge und kleinere Texte gefüllt. Außerdem habe ich der Familie jetzt "Kehricht" genannt. Wenn man mit dem mysteriösen Fundstück zu Gerrits Haus geht und dort mit desem spricht, crasht allerdings das Spiel bei mir. Ich weiß nicht woran das liegt. Diesen Bug bitte beheben und alles auf Rechtschreibfehler und Stimmigkeit überprüfen.

2017-07-04 15:57 UTC, JOOpdenhoevel requested changes
Gute Arbeit! Ich habe aber noch ein paar Änderungen, die aus meiner Sicht noch durchgeführt werden sollten.

2017-07-04 15:57 UTC, Janonard commented on Resources/Scenes/Gerrit/#0 with find.xml
> +    <delay time="3000" />
Die Zeiten sind etwas kurz, zu kurz, um den Text vernünftig zu lesen. Probier mal, die Texte laut vorzulesen und zu stoppen, wie lange du für die Zeilen brauchst.

2017-07-04 15:57 UTC, Janonard commented on Source/WindTurbine.py
> +        self.setObjectName("Kaputtes Windrad")
"Kaputtes" sollte klein geschrieben werden, ansonsten müsste man schreiben "sieh Kaputtes Windrad an". Eine Zeile darunter hast du es ja auch klein geschrieben.

2017-07-04 15:57 UTC, Janonard commented on Resources/Scenes/House3.xml
> +    <text>"Guten Tag, Ivy! Wir hatten mal eine Leiter auf der Nutzfläche. Möglicherweise findest du sie ja dort."</text>
Die "Nutzfläche" heißt mittlerweile "Feld", bitte anpassen.

2017-07-04 15:57 UTC, Janonard commented on Source/Ladder.py
> +        self.setObjectName("Wackelige Leiter")
Auch hier bitte "Wackelige" klein schreiben.

2017-07-04 15:57 UTC, Janonard commented on Resources/Scenes/Ending.xml
> +    <text>Vielen Dank fürs Spielen!</text>
Vielleicht sollte darin noch stehen, wer das Spiel gemacht hat, die Notiz "Copyright 2017: Jason "J2a0o0s0n" Becker, Jan-Oliver "Janonard" Opdenhövel und David "Flummi3" Waelsch" sollte reichen.

2017-07-04 16:03 UTC, Flummi3 commented
Wie ist das mit den Copyright-Anmerkungen? Soll ich mich in jede Datei wo ich etwas geändert habe reinschreiben? Weil das würde dann ja auch deine Programme betreffen, wo ich nur die einzelnen Texte verändert habe. Sonst habe ich ja eigentlich nur in strings und world gearbeitet.

2017-07-04 16:47 UTC, Janonard commented
In jede Datei, die du verändert hast, muss diese Notiz rein, egal wie klein die ist.

2017-07-04 16:48 UTC, J2a0s0o0n commented
@Flummi3, das ist ja richtig savage. Klasse Arbeit.

2017-07-04 16:57 UTC, J2a0s0o0n commented on Resources/Scenes/Ending.xml
> +    <text>Vielen Dank fürs Spielen!</text>
Ihr dürft mich auch Jason "J2a0s0o0n" Becker nennen.

2017-07-05 15:38 UTC, JOOpdenhoevel approved these changes

2017-07-05 15:38 UTC, merged